---
enabled: true
statefulset:
  extraVolumes:
    - name: custom-ca-bundle
      configMap: 
        name: custom-ca-bundle
  dind:
    tag: dind
    extraVolumeMounts:
      - name: custom-ca-bundle
        mountPath: /etc/docker/certs.d/registry.homelab.local
        readOnly: true
  actRunner:
    extraVolumeMounts:
      - name: custom-ca-bundle
        mountPath: /etc/docker/certs.d/registry.homelab.local
        readOnly: true
    config: |
      container:
        privileged: true
        network: "host"
        options: "-v /certs:/certs --env DOCKER_TLS_VERIFY=1 --env DOCKER_CERT_PATH=/certs/server --env DOCKER_HOST=tcp://127.0.0.1:2376"
        valid_volumes:
          - '**'
      runner:
        labels:
          - "ubuntu-latest:docker://sverdejot/act:latest"

existingSecret: actions-secret
existingSecretKey: key
giteaRootURL: http://gitea-http.gitea.svc.cluster.local:3000
