---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sverdejot-dot-dev-cert
  namespace: cert-manager
spec:
  secretName: sverdejot-dot-dev-tls
  issuerRef:
    name: sverdejot-dot-dev-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.sverdejot.dev"
