---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sverdejot-dot-dev-issuer
spec:
  acme:
    email: sverdejot@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: sverdejot-letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
