---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-custom
  namespace: argocd
  labels:
    app: argocd
spec:
  generators:
  - git:
    repoURL: https://github.com/sverdejot/beacon.git
    revision: HEAD
    directories:
    - path: manifests/*
  syncPolicy:
    applicationsSync: sync
  template:
    metadata:
      name: 'beacon-application'
      namespace: argocd
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/svedejot/beacon.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: beacon
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
