provider:
  name: pihole
policy: upsert-only
txtOwnerId: "homelab"
registry: noop
image:
  tag: v0.20.0
provider:
  name: pihole
env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    value: http://pihole-web.pihole-system.svc.cluster.local
serviceAccount:
  create: true
  name: "external-dns"
ingressClassFilters:
  - nginx
