---
repositories:
  - name: gitea-charts
    url: https://dl.gitea.com/charts/
---
releases:
  - name: gitea
    namespace: gitea
    chart: gitea-charts/gitea
    version: ~12
    values:
      - ./values/service.yml

  - name: gitea-actions
    namespace: gitea
    chart: gitea-charts/actions
    values:
      - ./values/actions.yml
