apiVersion: v1
kind: Secret
metadata:
    name: actions-secret
    namespace: gitea
type: Opaque
data:
    key: ENC[AES256_GCM,data:hw3GmMW48t3/Hi/9hyi9wWdDp6O3jzGKRwxSFEdwTdSLzVGJHKNxfpVnpOjFUVksNclH6uBjzKsg6Fxz0yJHIw==,iv:M2GrX61eUfY/KED7Y8KJBsxRdGDuIF2cBzcB4mKH8mM=,tag:O/TAyx8uWaXdhr8xK4NAOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SllzRjNnUmFxQkUyVXRv
            Y3hibUgwa3AwU0s0K2ZCaFpHdEN1aUZMb0NFCnNlZE1jSDcxL3ViTGRjWGg5NTVy
            VmJXeDBVR2tVYmVGRHdaM29UbmR2amMKLS0tIDlRY3dFQmRJcDlqVnZCWml5Z2c0
            Yk04eTdGQnBjckNaV1JuNmNGZ040U00KEQAQ90NmS6IbkNkrU9AKjC5KJNG3DIJy
            Aey6PpPUs3Q5IKqIrGZK/31WQjuoYh421sPOeV0BYv8+lNdgXp2gHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T22:35:41Z"
    mac: ENC[AES256_GCM,data:9550CX5gr2LAgI4p5iPZKIRWhLlfAczk0CYIlxV+EwLe8RVuzfsgZmhqSy65XzV/NgxRxN1lLc9V8RHhjiatnDcA8WuUqel6JSuZ1U0W+k8+CR+/gXNuWqwOtRmzqDBjqlsUfp6+k6MOT1YNl9DKx143nqS72J4cLoV8D5/wJ4k=,iv:o+9elHPoOxpK8Z+dS3GBaXdua8oj382mn/f5r8RlFyA=,tag:5RI/7ZU8wND6jjPXT1R3RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
